env:
  browser: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "next"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "prettier"
rules:
  {
    max-len: ["error", { "code": 80 }],
    no-console: warn,
    no-debugger: warn,
    semi: ["error", "never"],
    "sort-imports":
      [
        "error",
        {
          "ignoreCase": true,
          "ignoreDeclarationSort": false,
          "ignoreMemberSort": false,
          "memberSyntaxSortOrder": ["all", "single", "multiple", "none"],
          "allowSeparatedGroups": true,
        },
      ],
    quotes: ["error", "single"],
    prettier/prettier: error,
    "react/react-in-jsx-scope": "off",
    "react/jsx-filename-extension":
      [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
  }
